In [1]:
from pettingzoo.mpe import simple_spread_v3

env = simple_spread_v3.parallel_env(render_mode="rgb_array")
observations, infos = env.reset()
# env.observation_spaces
print(env.action_spaces)
# raise
while env.agents:
    # this is where you would insert your policy
    actions = {agent: env.action_space(agent).sample() for agent in env.agents}

    observations, rewards, terminations, truncations, infos = env.step(actions)
    print(terminations)
env.close()

{'agent_0': Discrete(5), 'agent_1': Discrete(5), 'agent_2': Discrete(5)}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2': False}
{'agent_0': False, 'agent_1': False, 'agent_2':

/home/mip012/anaconda3/envs/swarmrescue/lib/python3.10/site-packages/pettingzoo/utils/conversions.py:158: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
  warnings.warn(


In [4]:
x = 1 + 2*False
x

1

In [1]:
import sys 
sys.path.append("../")
sys.path.append("../..")
from multi_env.multi_agent import MultiSwarmEnv
import supersuit as ss

In [17]:
config = {
    "algo": "PPO",
    "policy_type": "MultiInputPolicy",
    "total_timesteps": 300_000,
    "env_name": "SwarmEnv-v0",
    "map_name": "Easy",
    "num_envs": 2,
    "continuous_action": True,
}

In [18]:
env = MultiSwarmEnv(n_agents=3, n_targets=3)
env = ss.pettingzoo_env_to_vec_env_v1(env)
envs = ss.concat_vec_envs_v1(env, config["num_envs"] , num_cpus=0, base_class="stable_baselines3")
from stable_baselines3 import PPO

In [21]:
model = PPO(env=envs, policy="MultiInputPolicy")

In [25]:
envs.reset()

OrderedDict([('lidar',
              array([[  9.7261715 ,   5.4823575 ,   5.764752  , ...,  10.080277  ,
                        6.0778785 ,   5.6444583 ],
                     [ 90.24835   ,  90.2476    ,  92.82695   , ...,  85.264534  ,
                       88.892815  ,  86.83108   ],
                     [ 87.26706   ,  86.15124   ,  85.215034  , ..., 232.75748   ,
                       93.47539   ,  87.15896   ],
                     [  0.56404006,  -0.5327782 ,  -1.1494119 , ...,   1.8496302 ,
                       -1.6996598 ,   2.169142  ],
                     [137.54149   , 143.89249   , 144.14903   , ..., 135.63187   ,
                      134.18741   , 135.3113    ],
                     [ 16.665382  ,  11.202607  ,  10.80861   , ...,  13.2270355 ,
                       16.391191  ,  11.419485  ]], dtype=float32)),
             ('pose',
              array([[  74.46803  , -112.41656  ,    1.6851834],
                     [ 119.322945 , -111.51247  ,    1.9282236],
   

In [28]:

# env.envs
from swarm_rescue.tools import progress_bar


model.learn(total_timesteps=100, progress_bar=True)


In [14]:
from stable_baselines3.common.vec_env import (
    DummyVecEnv,
    VecVideoRecorder,
    SubprocVecEnv,
)
from stable_baselines3.common.monitor import Monitor

def make_env():
    env = MultiSwarmEnv(
        map_name=config["map_name"],
        continuous_action=config["continuous_action"],
        fixed_step=30,
        max_episode_steps=50,
    )
    env = ss.pettingzoo_env_to_vec_env_v1(env)
    env = Monitor(env)
    return env

env = SubprocVecEnv([make_env for i in range(config["num_envs"])], start_method="fork")

X connection to :1 broken (explicit kill or server shutdown).
X connection to :1 broken (explicit kill or server shutdown).
X connection to :1 broken (explicit kill or server shutdown).
X connection to :1 broken (explicit kill or server shutdown).


ConnectionResetError: [Errno 104] Connection reset by peer

In [6]:
import numpy as np
x = np.random.randint(0, 10, size=(5, 3))
print(x)
x = np.array(sorted(x, key=lambda x: x[2]))
x[:,:2]

[[8 8 2]
 [3 2 2]
 [8 3 3]
 [4 5 0]
 [3 6 4]]


array([[4, 5],
       [8, 8],
       [3, 2],
       [8, 3],
       [3, 6]])